### ISSUE TITLE
curl_setopt(): Disabling safe uploads is no longer supported

### ISSUE THREAD

**Issue by samokoder** [StacoNiK/php-vk-api#1]
Привет.
В PHP 7.0 и выше опция `CURLOPT_SAFE_UPLOAD` удалена.
Выдает warning
`PHP Warning: curl_setopt(): Disabling safe uploads is no longer supported in vendor/staconik/php-vk-api/src/VKApi/Util/HttpClient.php on line 14`

**Comment by StacoNiK** [comment]
Исправлено.

**Comment by comandante-fidel** [comment]
Не исправлено.
Чтобы исправить, следует сделать следующее:

1. Вы поставили неверный оператор сравнения в файле HttpClient.php. Нужно его изменить.
Вот как у вас сейчас:
`if (version_compare(PHP_VERSION, '5.5.0', '>=')) {`
Вот как надо:
`if (version_compare(PHP_VERSION, '5.5.0', '<=')) {`

2. Необходимо внести правки в BasePhotoUpload.php.
Вот как у вас сейчас:
`$params = [$this->key_filename => "@".$rand_name];`
Вот как надо:
`if (version_compare(PHP_VERSION, '5.5.0', '<=')) {`
`   $params = [$this->key_filename => "@".$rand_name];`
` }`
`else {`
`   $params = [$this->key_filename => curl_file_create($rand_name)];`
` }`

Исправьте, пожалуйста. Спасибо!
