### ISSUE TITLE
Надо бы пофиксить ;)

### ISSUE THREAD

**Issue by AndreyKluev** [StacoNiK/php-vk-api#5]
https://github.com/StacoNiK/php-vk-api/blob/2acf3d005eb54644f1ffd381ea655949c7d049c6/src/VKApi/VkResponse.php#L21

**Comment by StacoNiK** [comment]
https://github.com/StacoNiK/php-vk-api/commit/47cf60dbb7d39ab95ac2e212df0bcdd51bad4f20
